language: php
php:
  - 5.5

script: phpunit --configuration test/Unit/phpunit.xml --coverage-text test/Unit

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

notifications:
  email:
    - info@gorka.io